name = "DocsBuilder"
uuid = "b8bfca86-1a58-5ed7-a9f0-ffd33e28453d"
authors = ["Rratic"]
version = ""

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
TOML = "1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
